// <auto-generated />
using System;
using EfCore.Queries.NonTrackedEntities.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCore.Queries.NonTrackedEntities.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20231119142101_AddBook")]
    partial class AddBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCore.Queries.NonTrackedEntities.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea165f8-69e5-4605-b45b-1e66227445ba"),
                            Title = "Asp.NET Core in Action"
                        },
                        new
                        {
                            Id = new Guid("d0ba9d76-f454-41b6-aad8-23dcea4ef167"),
                            Title = "C# 12 and .Net 8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
